package com.tamnt.mockito.examples.service.entity;

import javax.persistence.*;
import java.util.Date;

/**
 * CoinAccount generated by hbm2java
 */
@Entity
@Table(name = "coin_account", schema = "examples")
public class CoinAccount implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private String accountNumber;
    private Date createdDate;
    private Date updatedDate;
    private boolean useAffiliate;

    public CoinAccount() {
    }

    public CoinAccount(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "account_number", unique = true, nullable = false)
    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 29)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_date", length = 29)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    @Column(name = "use_affiliate")
    public boolean isUseAffiliate() {
        return useAffiliate;
    }

    public void setUseAffiliate(boolean useAffiliate) {
        this.useAffiliate = useAffiliate;
    }

}
